// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicWaterConsumption,
  DefaultWaterConsumptionProps,
} from "../plasmic/apa_nova_app/PlasmicWaterConsumption";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { ROUTES, STYLING } from "../../utils/CONST";
import useAppNavigation from "../../hooks/useAppNavigation";
import { IndexInput } from "../proprietary/IndexInput";
import useDefaultQueries from "../../hooks/useDefaultQueries";
import SkeletonLoader, {
  SkeletonLoaderProps,
} from "../proprietary/skeletons/SkeletonLoader";
import { useAppCtx } from "../../contexts/AppCtxProvider";
import ConsumptionIndexCard from "../ConsumptionIndexCard";
import { makeButtonLoader } from "./Homepage";

const { SKELETON_PRIMARY_COLOR } = STYLING;

export interface WaterConsumptionProps extends DefaultWaterConsumptionProps {}

function WaterConsumption_(
  props: WaterConsumptionProps,
  ref: HTMLElementRefOf<"div">
) {
  const { goBackTo } = useAppNavigation();
  const { userToken } = useAppCtx();
  const { consumption, user, latestBill } = useDefaultQueries(userToken);

  const isLoading = !consumption.isSuccess || !user.isSuccess;
  const buttonLoader = makeButtonLoader(isLoading);
  const componentLoader = (
    key: string,
    skeletonProps: SkeletonLoaderProps,
    children?: React.ReactNode
  ) => ({
    // @ts-expect-error
    render: (props, Component) =>
      isLoading ? (
        <SkeletonLoader key={`${key}-skeleton`} {...skeletonProps} />
      ) : (
        <Component
          key={`${key}-component`}
          {...props}
          children={children ? children : props.children}
        />
      ),
  });

  const { apartmentNo } = user.data || {};
  const {
    total,
    prevIndexWC,
    prevIndexBathroom,
    prevIndexKitchen,
    indexWC,
    indexBathroom,
    indexKitchen,
    consumptionCubeM,
  } = consumption.data || {};
  const { total: totalBill, waterConsumption } = latestBill.data || {};
  const pricePerCubeM = ((totalBill || 1) / (waterConsumption || 1)).toFixed(2);

  const [stateWC, setStateWC] = React.useState(indexWC);
  const [isValidWC, setIsValidWC] = React.useState(true);

  const [stateBathroom, setStateBathroom] = React.useState(indexBathroom);
  const [isValidBathroom, setIsValidBathroom] = React.useState(true);

  const [stateKitchen, setStateKitchen] = React.useState(indexKitchen);
  const [isValidKitchen, setIsValidKitchen] = React.useState(true);

  React.useEffect(() => {
    if (indexWC !== undefined) {
      setStateWC(indexWC);
    }
    if (indexBathroom !== undefined) {
      setStateBathroom(indexBathroom);
    }
    if (indexKitchen !== undefined) {
      setStateKitchen(indexKitchen);
    }
  }, [indexWC, indexBathroom, indexKitchen]);

  // TODO : Remove this
  const [hasUpdated, setHasUpdated] = React.useState(false);

  const consumptionValues = [
    {
      name: "WC",
      oldIndex: prevIndexWC,

      state: stateWC,
      setState: setStateWC,

      isValid: isValidWC,
      setIsValid: setIsValidWC,
    },
    {
      name: "Baie",
      oldIndex: prevIndexBathroom,

      state: stateBathroom,
      setState: setStateBathroom,

      isValid: isValidBathroom,
      setIsValid: setIsValidBathroom,
    },
    {
      name: "Bucătărie",
      oldIndex: prevIndexKitchen,

      state: stateKitchen,
      setState: setStateKitchen,

      isValid: isValidKitchen,
      setIsValid: setIsValidKitchen,
    },
  ] as const;

  return (
    <PlasmicWaterConsumption
      root={{ ref }}
      {...props}
      backButton={{
        onClick() {
          goBackTo(ROUTES.HOMEPAGE);
        },
      }}
      consumptionIndexCard={{
        render: () =>
          consumptionValues.map(
            (
              { name, oldIndex, state, setState, isValid, setIsValid },
              elIdx
            ) => (
              <ConsumptionIndexCard
                key={`consumption-card-${elIdx}`}
                nth={elIdx}
                isLoading={isLoading}
                consumptionPlace={name}
                consumptionIndex={` ${oldIndex}`}
                digitsInput={
                  state !== undefined &&
                  oldIndex !== undefined && (
                    <IndexInput
                      key={`digitsInput-${elIdx}`}
                      currIndexVal={state}
                      setCurrIndexVal={
                        setState as React.Dispatch<React.SetStateAction<number>>
                      }
                      isValid={isValid}
                      setIsValid={setIsValid}
                      prevIndexVal={oldIndex}
                    />
                  )
                }
              />
            )
          ),
      }}
      title={componentLoader(
        "title",
        {
          containerStyle: {
            width: "50vw",
          },
          height: "var(--plasmic-token-title)",

          ...SKELETON_PRIMARY_COLOR,
        },
        <div>{`Apartament ${apartmentNo}`}</div>
      )}
      enterIdxBtn={buttonLoader(
        () => {
          setHasUpdated(true);
        },
        {},
        SKELETON_PRIMARY_COLOR,
        {
          isLoading: hasUpdated,
        }
      )}
      totalText={`${total} LEI`}
      waterConsumption={`${consumptionCubeM} m³`}
      priceBreakdown={`${pricePerCubeM} lei / m³ = ${totalBill} lei / ${waterConsumption} m³`}
      totalBreakdown={{
        // TODO: Smarter hiding of the total breakdown
        render: (props, Component) => !isLoading && <Component {...props} />,
      }}
    />
  );
}

const WaterConsumption = React.forwardRef(WaterConsumption_);
export default WaterConsumption;
