// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicWaterConsumption,
  DefaultWaterConsumptionProps,
} from "../plasmic/apa_nova_app/PlasmicWaterConsumption";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { ROUTES } from "../../utils/CONST";
import useAppNavigation from "../../hooks/useAppNavigation";
import { IndexInput } from "../proprietary/IndexInput";

export interface WaterConsumptionProps extends DefaultWaterConsumptionProps {}

function WaterConsumption_(
  props: WaterConsumptionProps,
  ref: HTMLElementRefOf<"div">
) {
  const { goBackTo } = useAppNavigation();

  const consumptionValues = [
    {
      name: "WC",
      oldIndex: "1234",
    },
    {
      name: "Baie",
      oldIndex: "4567",
    },
    {
      name: "Bucătărie",
      oldIndex: "7890",
    },
  ] as const;

  return (
    <PlasmicWaterConsumption
      root={{ ref }}
      {...props}
      backButton={{
        onClick() {
          goBackTo(ROUTES.HOMEPAGE);
        },
      }}
      consumptionIndexCard={{
        render: (props, ConsumptionIdxCard) =>
          consumptionValues.map(({ name, oldIndex }, elIdx) => (
            <ConsumptionIdxCard
              {...props}
              key={elIdx}
              consumptionPlace={name}
              consumptionIndex={oldIndex}
              digitsInput={<IndexInput />}
            />
          )),
      }}
      apartmentNumber={"11"}
      totalText={"10.000 LEI"}
      waterConsumption={"2000 MC"}
      priceBreakdown={"7.4 = 74 / 10"}
    />
  );
}

const WaterConsumption = React.forwardRef(WaterConsumption_);
export default WaterConsumption;
