// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicErrorMessage,
  DefaultErrorMessageProps,
} from "./plasmic/apa_nova_app/PlasmicErrorMessage";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface ErrorMessageProps extends DefaultErrorMessageProps {}

function ErrorMessage_(props: ErrorMessageProps, ref: HTMLElementRefOf<"div">) {
  return <PlasmicErrorMessage root={{ ref }} {...props} />;
}

const ErrorMessage = React.forwardRef(ErrorMessage_);
export default ErrorMessage;
