// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicWaterConsumption,
  DefaultWaterConsumptionProps,
} from "./plasmic/apa_nova_app/PlasmicWaterConsumption";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

export interface WaterConsumptionProps extends DefaultWaterConsumptionProps {}

function WaterConsumption_(
  props: WaterConsumptionProps,
  ref: HTMLElementRefOf<"div">
) {
  return (
    <PlasmicWaterConsumption
      root={{ ref }}
      {...props}
      backButton={{
        onClick() {
          // eslint-disable-next-line
          history.back();
        },
      }}
    />
  );
}

const WaterConsumption = React.forwardRef(WaterConsumption_);
export default WaterConsumption;
